#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# Remove euro-office-etc volume to make the nginx update work
podman volume rm -f euro-office-etc

systemctl --user try-restart euro-office.service
